pipeline {
    agent any   // 👈 Run pipeline on Jenkins host

    stages {

        stage('Checkout') {
            steps {
                echo "Checkout completed"
            }
        }

        stage('Build and Test') {
            agent {
                docker {
                    image 'alphaman02/maven-docker-agent:v1'
                    args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
                }
            }
            steps {
                sh '''
                cd Spring-boot-app
                mvn clean package
                '''
            }
        }

        stage('Static Code Analysis') {
            agent {
                docker {
                    image 'alphaman02/maven-docker-agent:v1'
                    args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
                }
            }
            environment {
                SONAR_URL = "http://13.201.15.100:9000"
            }
            steps {
                withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_AUTH_TOKEN')]) {
                    sh '''
                    cd Spring-boot-app
                    mvn clean verify sonar:sonar \
                      -Dsonar.login=$SONAR_AUTH_TOKEN \
                      -Dsonar.host.url=$SONAR_URL
                    '''
                }
            }
        }

        stage('Build and Push Docker Image') {
            environment {
                DOCKER_IMAGE = "alphaman02/cicd:${BUILD_NUMBER}"
            }
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-cred',
                                 usernameVariable: 'DOCKER_USER',
                                 passwordVariable: 'DOCKER_PASS')]) {

                    sh '''
                    cd Spring-boot-app
                    docker build -t $DOCKER_IMAGE .
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    docker push $DOCKER_IMAGE
                    '''
                }
            }
        }

        stage('Update Deployment File') {
            steps {
                withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                    sh '''
                    git config user.email "phoenixanand02@gmail.com"
                    git config user.name "Anand"

                    sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" spring-boot-manifest/deployment.yml

                    git add spring-boot-manifest/deployment.yml
                    git commit -m "Update deployment image to version ${BUILD_NUMBER}" || echo "No changes to commit"

                    git push https://x-access-token:${GITHUB_TOKEN}@github.com/phoenixanand/cicd-jenkins-argocd-project HEAD:main
                    '''
                }
            }
        }
    }
}
